// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NotificationClient is the client API for Notification service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationClient interface {
	Notification(ctx context.Context, in *NotificationReq, opts ...grpc.CallOption) (Notification_NotificationClient, error)
}

type notificationClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationClient(cc grpc.ClientConnInterface) NotificationClient {
	return &notificationClient{cc}
}

func (c *notificationClient) Notification(ctx context.Context, in *NotificationReq, opts ...grpc.CallOption) (Notification_NotificationClient, error) {
	stream, err := c.cc.NewStream(ctx, &Notification_ServiceDesc.Streams[0], "/proto.Notification/Notification", opts...)
	if err != nil {
		return nil, err
	}
	x := &notificationNotificationClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Notification_NotificationClient interface {
	Recv() (*NotificationRes, error)
	grpc.ClientStream
}

type notificationNotificationClient struct {
	grpc.ClientStream
}

func (x *notificationNotificationClient) Recv() (*NotificationRes, error) {
	m := new(NotificationRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NotificationServer is the server API for Notification service.
// All implementations must embed UnimplementedNotificationServer
// for forward compatibility
type NotificationServer interface {
	Notification(*NotificationReq, Notification_NotificationServer) error
	mustEmbedUnimplementedNotificationServer()
}

// UnimplementedNotificationServer must be embedded to have forward compatible implementations.
type UnimplementedNotificationServer struct {
}

func (UnimplementedNotificationServer) Notification(*NotificationReq, Notification_NotificationServer) error {
	return status.Errorf(codes.Unimplemented, "method Notification not implemented")
}
func (UnimplementedNotificationServer) mustEmbedUnimplementedNotificationServer() {}

// UnsafeNotificationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServer will
// result in compilation errors.
type UnsafeNotificationServer interface {
	mustEmbedUnimplementedNotificationServer()
}

func RegisterNotificationServer(s grpc.ServiceRegistrar, srv NotificationServer) {
	s.RegisterService(&Notification_ServiceDesc, srv)
}

func _Notification_Notification_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NotificationReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NotificationServer).Notification(m, &notificationNotificationServer{stream})
}

type Notification_NotificationServer interface {
	Send(*NotificationRes) error
	grpc.ServerStream
}

type notificationNotificationServer struct {
	grpc.ServerStream
}

func (x *notificationNotificationServer) Send(m *NotificationRes) error {
	return x.ServerStream.SendMsg(m)
}

// Notification_ServiceDesc is the grpc.ServiceDesc for Notification service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Notification_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Notification",
	HandlerType: (*NotificationServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Notification",
			Handler:       _Notification_Notification_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "myproto.proto",
}
