// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CalcClient is the client API for Calc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalcClient interface {
	Add(ctx context.Context, in *CalcReq, opts ...grpc.CallOption) (*CalcRes, error)
	Minus(ctx context.Context, in *CalcReq, opts ...grpc.CallOption) (*CalcRes, error)
	Product(ctx context.Context, in *CalcReq, opts ...grpc.CallOption) (*CalcRes, error)
	Div(ctx context.Context, in *CalcReq, opts ...grpc.CallOption) (*CalcRes, error)
}

type calcClient struct {
	cc grpc.ClientConnInterface
}

func NewCalcClient(cc grpc.ClientConnInterface) CalcClient {
	return &calcClient{cc}
}

func (c *calcClient) Add(ctx context.Context, in *CalcReq, opts ...grpc.CallOption) (*CalcRes, error) {
	out := new(CalcRes)
	err := c.cc.Invoke(ctx, "/proto.Calc/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calcClient) Minus(ctx context.Context, in *CalcReq, opts ...grpc.CallOption) (*CalcRes, error) {
	out := new(CalcRes)
	err := c.cc.Invoke(ctx, "/proto.Calc/Minus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calcClient) Product(ctx context.Context, in *CalcReq, opts ...grpc.CallOption) (*CalcRes, error) {
	out := new(CalcRes)
	err := c.cc.Invoke(ctx, "/proto.Calc/Product", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calcClient) Div(ctx context.Context, in *CalcReq, opts ...grpc.CallOption) (*CalcRes, error) {
	out := new(CalcRes)
	err := c.cc.Invoke(ctx, "/proto.Calc/Div", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalcServer is the server API for Calc service.
// All implementations must embed UnimplementedCalcServer
// for forward compatibility
type CalcServer interface {
	Add(context.Context, *CalcReq) (*CalcRes, error)
	Minus(context.Context, *CalcReq) (*CalcRes, error)
	Product(context.Context, *CalcReq) (*CalcRes, error)
	Div(context.Context, *CalcReq) (*CalcRes, error)
	mustEmbedUnimplementedCalcServer()
}

// UnimplementedCalcServer must be embedded to have forward compatible implementations.
type UnimplementedCalcServer struct {
}

func (UnimplementedCalcServer) Add(context.Context, *CalcReq) (*CalcRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedCalcServer) Minus(context.Context, *CalcReq) (*CalcRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Minus not implemented")
}
func (UnimplementedCalcServer) Product(context.Context, *CalcReq) (*CalcRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Product not implemented")
}
func (UnimplementedCalcServer) Div(context.Context, *CalcReq) (*CalcRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Div not implemented")
}
func (UnimplementedCalcServer) mustEmbedUnimplementedCalcServer() {}

// UnsafeCalcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalcServer will
// result in compilation errors.
type UnsafeCalcServer interface {
	mustEmbedUnimplementedCalcServer()
}

func RegisterCalcServer(s grpc.ServiceRegistrar, srv CalcServer) {
	s.RegisterService(&Calc_ServiceDesc, srv)
}

func _Calc_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalcReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalcServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Calc/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalcServer).Add(ctx, req.(*CalcReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calc_Minus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalcReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalcServer).Minus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Calc/Minus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalcServer).Minus(ctx, req.(*CalcReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calc_Product_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalcReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalcServer).Product(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Calc/Product",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalcServer).Product(ctx, req.(*CalcReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calc_Div_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalcReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalcServer).Div(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Calc/Div",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalcServer).Div(ctx, req.(*CalcReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Calc_ServiceDesc is the grpc.ServiceDesc for Calc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Calc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Calc",
	HandlerType: (*CalcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Calc_Add_Handler,
		},
		{
			MethodName: "Minus",
			Handler:    _Calc_Minus_Handler,
		},
		{
			MethodName: "Product",
			Handler:    _Calc_Product_Handler,
		},
		{
			MethodName: "Div",
			Handler:    _Calc_Div_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "myproto.proto",
}
